#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
SAFE_SELF="/usr/local/bin/minecraftctl"

WORKING_DIRECTORY="/opt/minecraft"
MINECRAFT_USER="minecraft"
SYSTEMD_UNIT_NAME="minecraft"

print_help () {
	echo "Usage: $(basename "$0") [start|stop|restart|status|console|enable|disable] INSTANCE" >&2
	echo "    OR $(basename "$0") create NEW_INSTANCE SERVER_JAR" >&2
}

if [[ $# -eq 0 ]]
then
	print_help
	exit
fi


if [[ $# -eq 2 && "$2" =~ ^[[:alnum:]_-]+$ && -d "/opt/$SYSTEMD_UNIT_NAME/$2" ]]
then
	if [[ "$1" = console ]]
	then
		if [[ "$(id -un)" = "$MINECRAFT_USER" ]]
		then
			script -c "screen -x $2" /dev/null
		else
			sudo -n -u "$MINECRAFT_USER" "$SAFE_SELF" console "$2"
		fi
	elif [[ $1 =~ ^(start|stop|restart|status|enable|disable)$ ]]
	then
		if [[ "$(id -u)" -eq 0 ]]
		then
			systemctl "$1" "$SYSTEMD_UNIT_NAME@$2.service"
			code=$?
			if [[ "$1" != status ]]
			then
				[[ "$code" -eq 0 ]] && echo "OK" || echo "ERROR"
			fi
		else
			sudo -n "$SAFE_SELF" "$1" "$2"
		fi
	else
		print_help
		exit 1
	fi
elif [[ $# -eq 3 && "$1" = create && "$2" =~ ^[[:alnum:]_-]+$ && ! -d "$WORKING_DIRECTORY/$2" && -f "$3" && -r "$3" ]]
then
	if [[ $(id -un) = "$MINECRAFT_USER" ]]
	then
		mkdir "$WORKING_DIRECTORY/$2"
		cp "$3" "$WORKING_DIRECTORY/$2/$3"
		if [[ "$3" != minecraft_server.jar ]]
		then
			ln -s "$3" "$WORKING_DIRECTORY/$2/minecraft_server.jar"
		fi
		echo "eula=true" > "$WORKING_DIRECTORY/$2/eula.txt"
	else
		sudo -n -u "$MINECRAFT_USER" "$SAFE_SELF" create "$2" "$3"
	fi
else
	print_help
	exit 1
fi
