#!/bin/bash
set -euo pipefail
IFS=$'\n\t'

if [[ $# -gt 2 ]]; then
  exit 1
fi

version="${1:-"$(wget -q -O - https://papermc.io/api/v1/paper | jq -r '.versions[]' | sort -Vr | head -n1)"}"
build="${2:-"$(wget -q -O - https://papermc.io/api/v1/paper/"$version" | jq -r '.builds.latest')"}"

echo "downloading paper binary for minecraft version $version build $build"

wget -q -O "paper-$version-$build.jar" "https://papermc.io/api/v1/paper/$version/$build/download"
